sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t joegitau/docker-react .

script:
  - docker run joegitau/docker-react npm run test -- --coverage

# DEPLOYMENT CONFIG - AWS

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-30902346"
#   bucket_path: "docker-react" # match app: vaue
#   on:
#    branch: master # only deploy from github master branch
#   access_key_id: €AWS_ACCESS_KEY # randomly genereated env configs within travis-ci
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY" # randomly genereated env configs within travis-ci